'use strict';

const { test, ok } = require('tap');
const lib = require('r-assign/lib');

const libKeys = Object.keys(lib);

const methods = [
	'any',
	'anyDate',
	'anyNumber',
	'array',
	'asAnyDate',
	'asDate',
	'asString',
	'assertType',
	'asyncFunc',
	'bigint',
	'boolean',
	'convertToAnyDate',
	'convertToDate',
	'convertToString',
	'date',
	'func',
	'getAny',
	'getAnyNumber',
	'getArrayOf',
	'getBigInt',
	'getBoolean',
	'getInstanceOf',
	'getIntersectionOf',
	'getLiteral',
	'getLiteralOf',
	'getNull',
	'getNullable',
	'getNumber',
	'getObjectOf',
	'getStrictObjectOf',
	'getString',
	'getSymbol',
	'getTupleOf',
	'getType',
	'getUnionOf',
	'instance',
	'intersection',
	'isAny',
	'isAnyDate',
	'isAnyNumber',
	'isArrayOf',
	'isAsyncFunction',
	'isBigInt',
	'isBoolean',
	'isDate',
	'isFunction',
	'isInstanceOf',
	'isIntersectionOf',
	'isKeyOf',
	'isLiteral',
	'isLiteralOf',
	'isNever',
	'isNull',
	'isNullable',
	'isNullish',
	'isNumber',
	'isObjectOf',
	'isOmitFrom',
	'isOptional',
	'isOptionalUndefined',
	'isPartial',
	'isPartialUndefined',
	'isPickFrom',
	'isPromiseOf',
	'isRecordOf',
	'isRequired',
	'isStrictObjectOf',
	'isString',
	'isSymbol',
	'isTemplateLiteralOf',
	'isTupleOf',
	'isTupleRestOf',
	'isUndefined',
	'isUnionOf',
	'keyof',
	'literal',
	'literals',
	'never',
	'nullable',
	'nulled',
	'nullish',
	'number',
	'object',
	'optional',
	'optionalUndef',
	'omit',
	'parseAny',
	'parseAnyNumber',
	'parseArrayOf',
	'parseBigInt',
	'parseBoolean',
	'parseInstanceOf',
	'parseIntersectionOf',
	'parseLiteral',
	'parseLiteralOf',
	'parseNull',
	'parseNullable',
	'parseNumber',
	'parseObjectOf',
	'parseStrictObjectOf',
	'parseString',
	'parseSymbol',
	'parseTupleOf',
	'parseType',
	'parseUnionOf',
	'partial',
	'partialUndef',
	'pick',
	'promise',
	'record',
	'required',
	'same',
	'setSame',
	'strictObject',
	'string',
	'symbol',
	'templateLiteral',
	'tuple',
	'tupleRest',
	'undef',
	'union'
];

test('rAssign lib exports', ({ end }) => {

	methods.forEach((method) => {
		ok(method in lib, `Checked key "${method}" is exported`);
	});

	libKeys.forEach((key) => {
		ok(methods.includes(key), `Exported key "${key}" is checked`);
	});

	end();
});