'use strict';

const { test, equal, ok } = require('tap');
const lib = require('r-assign/lib');

const methods = [
	'getAny',
	'getAnyNumber',
	'getArrayOf',
	'getBigInt',
	'getBoolean',
	'getInstanceOf',
	'getIntersectionOf',
	'getLiteral',
	'getLiteralOf',
	'getNull',
	'getNullable',
	'getNumber',
	'getObjectOf',
	'getOptional',
	'getStrictObjectOf',
	'getString',
	'getSymbol',
	'getTupleOf',
	'getType',
	'getUnionOf',
	'isAny',
	'isAnyNumber',
	'isArrayOf',
	'isBigInt',
	'isBoolean',
	'isFunction',
	'isInstanceOf',
	'isIntersectionOf',
	'isLiteral',
	'isLiteralOf',
	'isNull',
	'isNullable',
	'isNumber',
	'isObjectOf',
	'isOptional',
	'isOptionalUndefined',
	'isStrictObjectOf',
	'isString',
	'isSymbol',
	'isTupleOf',
	'isUndefined',
	'isUnionOf',
	'parseAny',
	'parseAnyNumber',
	'parseArrayOf',
	'parseBigInt',
	'parseBoolean',
	'parseInstanceOf',
	'parseIntersectionOf',
	'parseLiteral',
	'parseLiteralOf',
	'parseNull',
	'parseNullable',
	'parseNumber',
	'parseObjectOf',
	'parseOptional',
	'parseStrictObjectOf',
	'parseString',
	'parseSymbol',
	'parseTupleOf',
	'parseType',
	'parseUnionOf'
];

test('rAssign lib exports', ({ end }) => {
	equal(Object.keys(lib).length, methods.length);
	methods.forEach((method) => ok(method in lib));
	end();
});